//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizedResources.Localization.Module.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizedResources.Localization.Module.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic start 的本地化字符串。
        /// </summary>
        public static string AutomaticStart {
            get {
                return ResourceManager.GetString("AutomaticStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background color 的本地化字符串。
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill color 的本地化字符串。
        /// </summary>
        public static string FillBrushColor {
            get {
                return ResourceManager.GetString("FillBrushColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foreground color 的本地化字符串。
        /// </summary>
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General settings 的本地化字符串。
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 May be unsuccessful 的本地化字符串。
        /// </summary>
        public static string MayBeUnsuccessful {
            get {
                return ResourceManager.GetString("MayBeUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive 的本地化字符串。
        /// </summary>
        public static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke color 的本地化字符串。
        /// </summary>
        public static string StrokeBrushColor {
            get {
                return ResourceManager.GetString("StrokeBrushColor", resourceCulture);
            }
        }
    }
}
