//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizedResources.Localization.Module.SystemMonitor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizedResources.Localization.Module.SystemMonitor.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Display graphics 的本地化字符串。
        /// </summary>
        public static string DisplayGraphics {
            get {
                return ResourceManager.GetString("DisplayGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display options 的本地化字符串。
        /// </summary>
        public static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphic drawing density 的本地化字符串。
        /// </summary>
        public static string GraphicDrawingDensity {
            get {
                return ResourceManager.GetString("GraphicDrawingDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphic height 的本地化字符串。
        /// </summary>
        public static string GraphicHeight {
            get {
                return ResourceManager.GetString("GraphicHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphic width 的本地化字符串。
        /// </summary>
        public static string GraphicWidth {
            get {
                return ResourceManager.GetString("GraphicWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main window width 的本地化字符串。
        /// </summary>
        public static string MainWindowWidth {
            get {
                return ResourceManager.GetString("MainWindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor update frequency 的本地化字符串。
        /// </summary>
        public static string MonitorUpdateFrequency {
            get {
                return ResourceManager.GetString("MonitorUpdateFrequency", resourceCulture);
            }
        }
    }
}
